name: Linter

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-ruff:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v5"
      - name: ruff-action
        uses: astral-sh/ruff-action@v3.5.1
        strategy:
          fail-fast: false
  run-codespell:
    name: CodeSpell
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: CodeSpell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: nl.json
          ignore_words_list: hass